# Generated by Django 4.2.14 on 2024-07-29 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chitaristi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='title',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='title',
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='video',
        ),
        migrations.AddField(
            model_name='videogallery',
            name='video_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.IntegerField(),
        ),
    ]
