# Generated by Django 4.2.14 on 2024-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitaristi', '0002_delete_user_alter_event_options_alter_slider_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='order',
        ),
        migrations.AddField(
            model_name='slider',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
