# Generated by Django 4.2.14 on 2024-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitaristi', '0003_remove_slider_order_slider_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
