# Generated by Django 4.2.14 on 2024-07-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitaristi', '0005_delete_slider_alter_imagegallery_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='Descrierea nu este disponibilă'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
