# Generated by Django 4.2.14 on 2024-07-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitaristi', '0006_rename_end_date_event_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={},
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='order',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='title',
            field=models.CharField(default='No description available', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='gallery/images/'),
        ),
    ]
