# Generated by Django 4.2.14 on 2024-07-30 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chitaristi', '0007_alter_imagegallery_options_remove_imagegallery_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
