# Generated by Django 4.2.14 on 2024-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitaristi', '0009_videogallery_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogallery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
    ]
