# Generated by Django 4.2.14 on 2024-07-30 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chitaristi', '0010_alter_videogallery_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
