# Generated by Django 4.2.14 on 2024-07-31 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chitaristi', '0011_contact_sent_at_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
