# Generated by Django 4.2.14 on 2024-07-31 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chitaristi', '0012_imagegallery_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
